name: flutter_gettext
description:
version: 0.1.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  sprintf: ^4.0.0
  gettext: ^1.1.0
  gettext_parser: ^0.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
